### ISSUE TITLE
Publish to maven central

### ISSUE THREAD

**Issue by hani** [blackberry/Krackle#1]
Any chance of having releases published to maven central?

**Comment by jitpack** [comment]
If you like you can get it from https://jitpack.io/#blackberry/Krackle/0.7.7

**Comment by ariens** [comment]
Please note that Krackle, KaBoom, and Klogger have all have fairly major updates and those updates have now been pushed to Github.  Here's a summary:

KaBoom 0.7.2 (dev branch): https://github.com/ariens/KaBoom (Changes: https://github.com/ariens/KaBoom/blob/dev/docs/change-log.txt)
Krackle 0.7.10 (dev branch): https://github.com/ariens/Krackle (Changes:  https://github.com/ariens/Krackle/blob/dev/docs/change-log.txt)
Klogger 0.7.9 (dev branch): https://github.com/ariens/Klogger (Changes: https://github.com/ariens/Klogger/blob/dev/docs/change-log.txt)
Common-Utils 0.0.4 (master branch): https://github.com/ariens/BB-BigData-Common-Utils 
Test-Utils 0.0.1 (master branch) https://github.com/ariens/BB-BigData-Common-TestUtils

These project version are all currently residing under my personal space (not BlackBerry) for the time being until they can be pulled into the BB org's space accordingly.

I'm actively working on pushing these projects artifacts to Maven Central, however in the meantime, building each of these locally will provide all the artifacts for a deploying a fully functional high performance ingest/consumer stack around Kafka 0.8.1.1.
