### ISSUE TITLE
how to know whether the producer is good to go

### ISSUE THREAD

**Issue by DeanHere** [blackberry/Krackle#2]
The Producer.java does not throw an exception when updateMetaDataAndConnection method failed, and I would know the producer is not good if it could throw something out or set a flag for determining.

**Comment by ariens** [comment]
There are few invokations of updateMetaDataAndConnection().

1) In the Producer's constructor (if it fails, the metadata becomes null
2) In sendMessage() when the meta data is null (this is wrapped around a retry counter, with backoff interval)
3) Periodically In sendMessage() based off topicMetadataRefreshIntervalMs

Error handling of each scenario:

1) sendMessage() will see the null metadata and we enter into '2'
2) After totalRetries attempts, we log the  error and mark the failure meter
3) error logged

Keep in mind the metadata refresh uses the broker list to obtian it's metadata.  A failure/failover of a connected broker will cause another broker to take over and then successfully return metadata.  Broker failures are not uncommon and the metrics and logs suffice for monitoring stability
