### ISSUE TITLE
consumer.getMessage  just get one message once a time

### ISSUE THREAD

**Issue by shllove** [blackberry/Krackle#3]
consumer.getMessage  interact with the kafka server everytime when get one message, it should add one range message method.

**Comment by ariens** [comment]
Krackle employs a message set reader that will grab an entire compressed block of messages that will include the specific offset being requested.  That message set is the source of all subsequent getMessage() requests until the requested offset is outside of the cached message set.  Then, Kafka is queried for the next block of compressed offsets.  This should pretty much mitigate any requirement for fetching ranges of messages.
