### ISSUE TITLE
Is this still in maintenance?

### ISSUE THREAD

**Issue by DeanHere** [blackberry/Krackle#4]
Just would like to know if this is still in maintenance, or if there is some future plan.
And can I use 0.7.10 from ariens/Krackle in production env?
Thanks.

**Comment by ariens** [comment]
Hey there, Krackle is still very much in maintenance and a new version is dropping alongside kaboom and klogger imminently. Check back by end of week for the latest releases.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          From: DeanHereSent: Tuesday, April 21, 2015 9:33 PMTo: blackberry/KrackleReply To: blackberry/KrackleSubject: [Krackle] Is this still in maintenance? (#4)Just would like to know if this is still in maintenance, or if there is some future plan.
And can I use 0.7.10 from ariens/Krackle in production env?
Thanks.

—Reply to this email directly or view it on GitHub.

**Comment by DeanHere** [comment]
thanks.

**Comment by ariens** [comment]
Just pushed loads of updates, and included a the JARs in the release.
