### ISSUE TITLE
Missing dependency com.blackberry.bdp.common:bdp-common:jar:0.0.9

### ISSUE THREAD

**Issue by csebille** [blackberry/Krackle#5]
Hi,
  I have an issue while compilng Krackle : the 0.8.0 version needs com.blackberry.bdp.common:bdp-common:jar:0.0.9 but I don't know how to get it.

  Could you please tell me if this library is available ?
Regards,

Christophe

**Comment by ariens** [comment]
Hi Christophe!
Please check this out... We're not yet pushing our artifacts to maven central so in the meantime you'll need to obtain the specific BlackBerry projects from Github and build them locally installing them in your local maven repo.

https://github.com/blackberry/BB-BigData-Common-Utils
